name: conditional-os-matrix

on:
  push:
    branches:
      - test-conditional-os-matrix
  pull_request:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      os:
        description: 'OS to run on'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - macos-latest


jobs:
  set-up-os-matrix:
    name: "Set up OS matrix"
    runs-on: ubuntu-latest
    outputs:
      os_matrix: ${{ steps.step.outputs.os_matrix }}
    steps:
      - name: Set up OS matrix
        id: step
        run: |
          if [[ ${{ github.event_name }} = 'schedule' ]]; then
            MATRIX='["ubuntu-latest", "macos-latest"]'
          elif [[ ${{ github.event_name }} = 'workflow_dispatch' ]]; then
            MATRIX='["${{ inputs.os }}"]'
          else
            MATRIX='["ubuntu-latest"]'
          fi
          echo "$MATRIX"
          echo "os_matrix=$MATRIX" >> "$GITHUB_OUTPUT"

  do-work:
    name: "Do work"
    needs: set-up-os-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(needs.set-up-os-matrix.outputs.os_matrix) }}

    steps:
      - name: Print event info
        run: |
          echo github.event : ${{ github.event }}
          echo github.event_name : ${{ github.event_name }}
          echo github.event_path : ${{ github.event_path }}
          echo matrix.os : ${{ matrix.os }}
          echo runner.os : ${{ runner.os }}
