name: docs-main

on:
  workflow_dispatch:
    inputs:
      build:
        description: Whether to build "latest" from target branch
        required: false
        default: "true"
      deploy:
        description: Whether to deploy gh-pages to Netlify
        required: false
        default: "true"

jobs:
  build:
    name: Build docs from main branch
    if: ${{ github.event.inputs.build }} == 'true'
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build docs
        run: |
          make docs

      - name: Stage docs on gh-pages
        working-directory: docs
        run: |
          git fetch origin gh-pages --depth=1
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          mike deploy --push ~latest --title=latest

  deploy:
    name: Deploy docs to Netlify
    if: ${{ github.event.inputs.build }} == 'true'
    needs: build
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Deploy docs to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: "./"
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
