name: inspect-context

on:
  workflow_dispatch:

jobs:
  build:
    name: "Inspect Context"
    runs-on: ubuntu-latest

    steps:
      - name: Print event info
        run: |
          echo github.event ${{ github.event }}
          echo github.event_name ${{ github.event_name }}
          echo github.event_path ${{ github.event_path }}
