name: publish-settings

on:
  workflow_dispatch:
    inputs:
      publishDev:
        description: 'Publish image as cpu-{sha} and gpu-{sha}'
        required: true
        default: false
        type: boolean

jobs:
  build:
    name: Build, Test, and Publish Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        proc: ["cpu", "gpu"]
    env:
      SHOULD_PUBLISH_LATEST: ${{ github.ref == 'refs/heads/main' && vars.PUBLISH_LATEST_ON_MAIN != '' }}
      SHOULD_PUBLISH: |
        ${{
          github.ref == 'refs/heads/main' && vars.PUBLISH_LATEST_ON_MAIN != ''
          || github.event_name == 'workflow_dispatch' && inputs.publishDev
        }}
      SHA_TAG: ${{ matrix.proc }}-${{ github.sha }}
      LATEST_TAG: ${{ matrix.proc }}-latest

    steps:

      - name: Check SHOULD_PUBLISH
        if: ${{ fromJson(env.SHOULD_PUBLISH) }}
        run: |
          echo "hit"

      - name: Check SHOULD_PUBLISH_LATEST
        if: ${{ fromJson(env.SHOULD_PUBLISH_LATEST) }}
        run: |
          echo "hit"
