name: tests

on:
  workflow_dispatch:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint package
        run: |
          echo "Your code is alright."
          # echo "Your code stinks."
          # exit 1

  tests:
    name: "Tests: ${{ matrix.os }}, Python ${{ matrix.python-version }}"
    needs: code-quality
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Tests passed."

  notify:
    name: Notify failed build
    needs: [code-quality, tests]
    if: failure() && github.event.pull_request == null
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_NAME: ${{ github.workflow }}
          RUN_NUMBER: ${{ github.run_number}}
          REPOSITORY: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        with:
          filename: .github/failed_build_issue_template.md
